const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.QA_BASE_URL || 'http://127.0.0.1:4178';
const evidence = process.env.QA_EVIDENCE_DIR || '.pwc/evidence/about';
fs.mkdirSync(evidence, { recursive: true });
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1522, height: 736 } });
  const errors = [], checks = [];
  page.on('pageerror', error => errors.push(error.message));
  const pass = name => { checks.push(name); console.log('PASS', name); };
  const state = fn => page.evaluate(fn);
  const idle = () => page.waitForFunction(() => window.__replica.controller.rig.animation === 'idle');
  try {
    await page.goto(`${base}/?section=about`);
    await page.getByRole('button', { name: '挥挥手', exact: true }).waitFor();
    await page.waitForFunction(() => !document.querySelector('.cowcoming-model-controls button').disabled);
    await page.waitForFunction(() => window.__replica.controller.rig?.scale > 1.39);
    assert.equal(await state(() => window.__replica.controller.rig.asset), '/models/niulai-mouth.glb');
    assert.equal(await page.locator('.character-stage canvas').count(), 1);
    pass('About loads one Niulai model, never the former human avatar');
    const stage = await page.locator('.cowcoming-about-stage').boundingBox();
    const x = stage.x + stage.width / 2, y = stage.y + stage.height * .4;
    await page.mouse.move(stage.x + 15, y);
    await page.waitForFunction(() => window.__replica.controller.bodyYaw < -.3);
    await page.mouse.move(stage.x + stage.width - 15, y);
    await page.waitForFunction(() => window.__replica.controller.bodyYaw > .3);
    pass('cursor gaze uses the left model stage coordinates');
    await page.getByRole('button', { name: '光标跟随 · 开' }).click();
    await page.waitForFunction(() => Math.abs(window.__replica.controller.bodyYaw) < .05);
    await page.mouse.click(x, y);
    await page.waitForFunction(() => window.__replica.controller.rig.animation === 'wave');
    await idle();
    pass('clicking the actual model waves and returns to idle');
    await page.mouse.click(stage.x + 10, y);
    await page.waitForTimeout(300);
    assert.equal(await state(() => window.__replica.controller.rig.animation), 'idle');
    await page.getByRole('heading', { name: 'Cowcoming', exact: true }).click();
    await page.waitForTimeout(200);
    assert.equal(await state(() => window.__replica.controller.rig.animation), 'idle');
    pass('empty stage and project text clicks do not trigger gestures');
    await page.mouse.move(x, y);
    await page.mouse.down();
    await page.mouse.move(x + 100, y, { steps: 10 });
    assert.equal(await state(() => window.__replica.controller.dragging), true);
    await page.mouse.up();
    assert.equal(await state(() => window.__replica.controller.dragging), false);
    assert.equal(await state(() => window.__replica.controller.lastPointerWasDrag), true);
    await page.waitForTimeout(300);
    assert.equal(await state(() => window.__replica.controller.rig.animation), 'idle');
    pass('drag rotates and releases without triggering a tap');
    await page.getByRole('button', { name: '暂停动画' }).click();
    assert.equal(await page.getByRole('button', { name: '挥挥手', exact: true }).isDisabled(), true);
    await page.mouse.click(x, y);
    assert.equal(await state(() => window.__replica.controller.queue.pending), null);
    await page.getByRole('button', { name: '继续动画' }).click();
    await page.getByRole('button', { name: '挥挥手', exact: true }).focus();
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => window.__replica.controller.rig.animation === 'wave');
    await idle();
    pass('pause prevents queued clicks; keyboard greeting works after resume');
    await page.getByRole('button', { name: '光标跟随 · 关' }).click();
    await page.getByRole('button', { name: /About JEV|了解 JEV|JEV 介绍/ }).filter({visible: true}).first().click();
    await page.waitForFunction(() => window.__replica.getState().chat === 'open');
    await page.mouse.move(40, 200);
    assert.equal(await state(() => window.__replica.controller.mouse.active), false);
    await page.keyboard.press('Escape');
    await page.waitForFunction(() => window.__replica.getState().chat === 'closed');
    pass('modal interaction suspends model input and Escape returns to About');
    for (const [width, height] of [[1522,736],[1280,720],[900,700],[768,1024],[390,844],[320,740]]) {
      await page.setViewportSize({width,height});
      await page.locator('.page-host').evaluate(el => { el.scrollTop = 0; });
      await page.mouse.move(width/2, 80);
      await page.waitForTimeout(350);
      const layout = await state(() => {
        const host = document.querySelector('.page-host');
        const model = document.querySelector('.cowcoming-about-model').getBoundingClientRect();
        const copy = document.querySelector('.cowcoming-about-copy').getBoundingClientRect();
        return {overflow:host.scrollWidth>host.clientWidth, separate:innerWidth>768?model.right<=copy.left: model.bottom<=copy.top};
      });
      assert.equal(layout.overflow, false);
      assert.equal(layout.separate, true);
      await page.screenshot({ path: `${evidence}/about-${width}.png` });
    }
    pass('six viewport sizes have no horizontal overflow or model/copy overlap');
    await page.setViewportSize({width:390,height:844});
    await page.dispatchEvent('.character-stage canvas','pointerover',{pointerType:'touch',bubbles:true});
    await page.dispatchEvent('.character-stage canvas','pointermove',{pointerType:'touch',clientX:30,clientY:300,bubbles:true});
    assert.equal(await state(() => window.__replica.controller.mouse.active), false);
    await page.mouse.move(190,380);
    await page.mouse.wheel(0,600);
    await page.waitForFunction(() => document.querySelector('.page-host').scrollTop > 100);
    await page.getByRole('button', { name: '体验 Cowcoming' }).scrollIntoViewIfNeeded();
    await page.screenshot({path:`${evidence}/about-mobile-content.png`});
    pass('mobile can scroll past the model to the content and CTA');
    await page.getByRole('button', { name: '体验 Cowcoming' }).click();
    await page.waitForFunction(() => window.__replica.getState().mode === 'home');
    await page.getByRole('navigation').getByRole('button',{name:/^(ABOUT|关于)$/,exact:true}).click();
    await page.waitForFunction(() => !document.querySelector('.cowcoming-model-controls button').disabled);
    assert.equal(await page.locator('.character-stage canvas').count(), 1);
    await page.goBack();
    await page.waitForFunction(() => window.__replica.getState().mode === 'home');
    await page.goForward();
    await page.waitForFunction(() => window.__replica.getState().mode === 'about');
    assert.deepEqual(errors, []);
    pass('CTA, navigation, browser back/forward work without runtime errors');
    const failure = await browser.newPage();
    await failure.route('**/models/niulai-mouth.glb', route => route.abort());
    await failure.goto(`${base}/?section=about`);
    await failure.getByRole('alert').waitFor();
    assert.equal(await failure.getByRole('button',{name:'Reload scene'}).isVisible(), true);
    await failure.waitForFunction(() => getComputedStyle(document.querySelector('.character-stage')).opacity === '1');
    assert.equal(await failure.getByRole('heading',{name:'Cowcoming',exact:true}).isVisible(), true);
    await failure.close();
    pass('model load failure displays a visible retry and keeps project content available');
  } finally {
    fs.writeFileSync(`${evidence}/result.json`,JSON.stringify({checks,errors},null,2));
    await browser.close();
  }
})().catch(error=>{console.error(error);process.exitCode=1});
